import {describe, expect, test} from "vitest";

import {EMOJI_CATEGORIES} from "../src/emoji-data.ts";
import {EMOJI_GLYPH_BY_NAME} from "../src/emoji-glyphs.ts";

// The literal in src/emoji-glyphs.ts is generated by
// scripts/regen-emoji-glyphs.mjs from EMOJI_CATEGORIES. Locks in the
// invariant: both representations must agree. If this fails, someone
// added or removed an entry in emoji-data.ts without rerunning the
// generator.
describe("EMOJI_GLYPH_BY_NAME is in sync with EMOJI_CATEGORIES", () => {
    const derived: Record<string, string> = {};
    for (const cat of EMOJI_CATEGORIES) {
        for (const entry of cat.emojis) {
            derived[entry.name] = entry.glyph;
        }
    }

    test("every picker entry maps to its glyph", () => {
        for (const [name, glyph] of Object.entries(derived)) {
            expect(EMOJI_GLYPH_BY_NAME[name], `glyph for :${name}:`).toBe(glyph);
        }
    });

    test("no extra entries in the flat map", () => {
        for (const name of Object.keys(EMOJI_GLYPH_BY_NAME)) {
            expect(derived[name], `extra entry :${name}: in flat map`).toBeDefined();
        }
    });
});
