name: zulip_embed_example
description: Example app showing the zulip_embed Flutter package in use.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  zulip_embed:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
