// Compute SRI hashes + per-entry gzipped sizes for every dist/ artifact
// a host page is likely to load via `<script>` or unpkg.
//
// Emits two files the release workflow uses downstream:
//   - dist/INTEGRITY.json  — machine-readable manifest.
//   - dist/INTEGRITY.md    — markdown table ready to splice into
//                            README.md between <!-- sri:start -->
//                            and <!-- sri:end --> markers.
//
// Runs after `pnpm build`. Fails hard if any expected artifact is
// missing so a broken tarball never reaches npm.
//
// Zero runtime deps beyond the Node builtins listed below. Keep it
// that way — this script runs in CI before any workspace install has
// hydrated devDependencies for other packages.
//
// SRI digest format is `sha256-<base64>`, matching the shape the
// browser expects in `<script integrity="…" crossorigin>`. See
// https://developer.mozilla.org/docs/Web/Security/Subresource_Integrity.

import {createHash} from "node:crypto";
import {existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync} from "node:fs";
import {dirname, join, relative, resolve} from "node:path";
import {gzipSync} from "node:zlib";

const ROOT = resolve(import.meta.dirname, "..");
const DIST = join(ROOT, "dist");
const PKG = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));

function fail(message) {
    console.error(`release.mjs: ${message}`);
    process.exit(1);
}

if (!existsSync(DIST)) {
    fail("dist/ does not exist — run `pnpm build` first.");
}

// Canonical set of artifacts a host actually fetches. The IIFE is the
// single file unpkg serves; entries/*.js are the subpath ESM entries
// published in package.json#exports. Chunks are intentionally not
// listed — they're fingerprinted by filename and get pulled in only
// through the entries that import them.
const IIFE = "zulip-embed.iife.js";
const ENTRIES_DIR = join(DIST, "entries");

const artifactPaths = [IIFE];
if (existsSync(ENTRIES_DIR) && statSync(ENTRIES_DIR).isDirectory()) {
    const entries = readdirSync(ENTRIES_DIR)
        .filter((name) => name.endsWith(".js") && !name.endsWith(".map"))
        .sort();
    for (const name of entries) {
        artifactPaths.push(join("entries", name));
    }
} else {
    fail("dist/entries/ missing — build did not produce subpath entries.");
}

const missing = artifactPaths.filter((rel) => !existsSync(join(DIST, rel)));
if (missing.length > 0) {
    fail(`missing dist artifacts: ${missing.join(", ")}`);
}

function sriFor(bytes) {
    const digest = createHash("sha256").update(bytes).digest("base64");
    return `sha256-${digest}`;
}

function formatKb(bytes) {
    // One decimal place; enough signal without suggesting false precision.
    return `${(bytes / 1024).toFixed(1)} KB`;
}

function prettyLabel(rel) {
    if (rel === IIFE) return `\`${rel}\` (unpkg)`;
    // "entries/chat.js" → "`zulip-embed/chat`"
    if (rel.startsWith("entries/")) {
        const name = rel.slice("entries/".length).replace(/\.js$/, "");
        return `\`zulip-embed/${name}\``;
    }
    return `\`${rel}\``;
}

const artifacts = artifactPaths.map((rel) => {
    const abs = join(DIST, rel);
    const bytes = readFileSync(abs);
    const gz = gzipSync(bytes);
    const sri = sriFor(bytes);
    return {
        path: rel,
        sizeBytes: bytes.length,
        gzipBytes: gz.length,
        sha256: createHash("sha256").update(bytes).digest("hex"),
        integrity: sri,
    };
});

// External assets we load at runtime from a CDN (not bundled into dist/,
// but still part of the trust boundary a host page should be able to
// verify). Kept in lock-step with src/katex.ts — bump both in the same
// commit when upgrading KaTeX. See also the TODO(1.1) there to automate
// this fetch. The hash is re-asserted here instead of imported so this
// script stays dep-free (runs in CI before any workspace install).
const KATEX_VERSION = "0.16.11";
const externalAssets = [
    {
        name: "katex-css",
        url: `https://cdn.jsdelivr.net/npm/katex@${KATEX_VERSION}/dist/katex.min.css`,
        integrity: "sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+",
        loadedBy: "src/katex.ts",
        note: "Pinned KaTeX stylesheet injected into the shadow root when a message contains math.",
    },
];

const manifest = {
    name: PKG.name,
    version: PKG.version,
    buildTime: new Date().toISOString(),
    artifacts,
    externalAssets,
};

const manifestPath = join(DIST, "INTEGRITY.json");
writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

// Markdown table — columns match the README placeholder so the
// release workflow can splice this file in between the sri:start /
// sri:end markers with a straight substring replace.
const lines = [];
lines.push(`<!-- Generated by scripts/release.mjs for v${PKG.version} -->`);
lines.push("");
lines.push("| Entry | Size (gz) | SRI hash |");
lines.push("|-------|-----------|----------|");
for (const artifact of artifacts) {
    lines.push(
        `| ${prettyLabel(artifact.path)} | ${formatKb(artifact.gzipBytes)} | \`${artifact.integrity}\` |`,
    );
}
lines.push("");
const mdPath = join(DIST, "INTEGRITY.md");
writeFileSync(mdPath, lines.join("\n"));

// Console output: keep it short — CI log scanners prefer one summary
// line per artifact plus the two output paths.
console.log(`zulip-embed@${PKG.version} integrity manifest`);
console.log("-".repeat(72));
for (const artifact of artifacts) {
    console.log(
        `  ${artifact.path.padEnd(32)} ${formatKb(artifact.gzipBytes).padStart(9)}  ${artifact.integrity}`,
    );
}
console.log("-".repeat(72));
console.log(`wrote ${relative(ROOT, manifestPath)}`);
console.log(`wrote ${relative(ROOT, mdPath)}`);
