// Curated emoji dataset for the picker. Covers the glyphs Zulip's
// canonical emojiset renders; enough that almost every common reaction
// has a button without shipping the full ~3000-entry Unicode CLDR list
// in a browser bundle. Categories roughly match Zulip's own picker
// (People / Nature / Food / Activity / Travel / Objects / Symbols /
// Flags) so muscle memory carries over.
//
// Each entry is `{name, glyph, keywords}`:
//   - `name` is the Zulip emoji name we send to the server as a
//     reaction (must match a realm-registered name; the defaults here
//     match Zulip's built-in emojiset).
//   - `glyph` is what we render in the button and the textarea.
//   - `keywords` extends search — "party" finds "tada", etc.
//
// Adding more emojis later is cheap; just append to the right category.
// Names must stay stable because they're the wire format for reactions.

export type EmojiCategoryId =
    | "people"
    | "nature"
    | "food"
    | "activity"
    | "travel"
    | "objects"
    | "symbols"
    | "flags";

export interface EmojiEntry {
    name: string;
    glyph: string;
    keywords?: readonly string[];
}

export interface EmojiCategory {
    id: EmojiCategoryId;
    label: string;
    // Short text label for the category-nav strip. Single-character
    // glyphs keep the strip compact and recognizable at small widths.
    icon: string;
    emojis: readonly EmojiEntry[];
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
    {
        id: "people",
        label: "People",
        icon: "😀",
        emojis: [
            {name: "grinning", glyph: "😀", keywords: ["happy", "smile"]},
            {name: "smile", glyph: "😄", keywords: ["happy", "joy"]},
            {name: "laughing", glyph: "😂", keywords: ["lol", "haha", "laugh"]},
            {name: "rofl", glyph: "🤣", keywords: ["lol", "haha"]},
            {name: "blush", glyph: "😊", keywords: ["happy", "flushed"]},
            {name: "wink", glyph: "😉", keywords: ["flirt", "tease"]},
            {name: "heart_eyes", glyph: "😍", keywords: ["love"]},
            {name: "kissing_heart", glyph: "😘", keywords: ["kiss", "love"]},
            {name: "yum", glyph: "😋", keywords: ["tongue", "tasty"]},
            {name: "stuck_out_tongue", glyph: "😛", keywords: ["tongue"]},
            {name: "zany_face", glyph: "🤪", keywords: ["crazy", "silly"]},
            {name: "sunglasses", glyph: "😎", keywords: ["cool"]},
            {name: "nerd_face", glyph: "🤓", keywords: ["glasses", "smart"]},
            {name: "thinking", glyph: "🤔", keywords: ["hmm", "consider"]},
            {name: "zipper_mouth_face", glyph: "🤐", keywords: ["silent"]},
            {name: "neutral_face", glyph: "😐", keywords: ["meh"]},
            {name: "expressionless", glyph: "😑", keywords: ["meh"]},
            {name: "unamused", glyph: "😒", keywords: ["annoyed"]},
            {name: "rolling_eyes", glyph: "🙄", keywords: ["annoyed"]},
            {name: "grimacing", glyph: "😬", keywords: ["awkward"]},
            {name: "lying_face", glyph: "🤥", keywords: ["liar"]},
            {name: "relieved", glyph: "😌", keywords: ["phew", "calm"]},
            {name: "pensive", glyph: "😔", keywords: ["sad"]},
            {name: "sleepy", glyph: "😪", keywords: ["tired"]},
            {name: "sleeping", glyph: "😴", keywords: ["zzz"]},
            {name: "drooling_face", glyph: "🤤", keywords: ["tasty"]},
            {name: "mask", glyph: "😷", keywords: ["sick", "ill"]},
            {name: "face_with_thermometer", glyph: "🤒", keywords: ["sick"]},
            {name: "face_with_head_bandage", glyph: "🤕", keywords: ["hurt"]},
            {name: "nauseated_face", glyph: "🤢", keywords: ["sick"]},
            {name: "sneezing_face", glyph: "🤧", keywords: ["sick", "cold"]},
            {name: "hot_face", glyph: "🥵", keywords: ["hot"]},
            {name: "cold_face", glyph: "🥶", keywords: ["cold"]},
            {name: "dizzy_face", glyph: "😵", keywords: ["confused"]},
            {name: "exploding_head", glyph: "🤯", keywords: ["mind", "blown"]},
            {name: "cowboy", glyph: "🤠", keywords: ["cowboy"]},
            {name: "partying_face", glyph: "🥳", keywords: ["party", "birthday"]},
            {name: "party", glyph: "🥳", keywords: ["party", "birthday"]},
            {name: "smiling_face_with_hearts", glyph: "🥰", keywords: ["love"]},
            {name: "confused", glyph: "😕", keywords: ["puzzled"]},
            {name: "worried", glyph: "😟", keywords: ["sad"]},
            {name: "slightly_frowning_face", glyph: "🙁", keywords: ["sad"]},
            {name: "frowning_face", glyph: "☹️", keywords: ["sad"]},
            {name: "astonished", glyph: "😲", keywords: ["wow", "surprise"]},
            {name: "flushed", glyph: "😳", keywords: ["embarrassed"]},
            {name: "fearful", glyph: "😨", keywords: ["scared"]},
            {name: "cold_sweat", glyph: "😰", keywords: ["scared"]},
            {name: "cry", glyph: "😢", keywords: ["sad", "tear"]},
            {name: "sob", glyph: "😭", keywords: ["crying", "sad"]},
            {name: "scream", glyph: "😱", keywords: ["shock"]},
            {name: "rage", glyph: "😡", keywords: ["angry", "mad"]},
            {name: "pouting_face", glyph: "😡", keywords: ["angry"]},
            {name: "triumph", glyph: "😤", keywords: ["frustrated"]},
            {name: "poop", glyph: "💩", keywords: ["shit"]},
            {name: "imp", glyph: "👿", keywords: ["devil"]},
            {name: "skull", glyph: "💀", keywords: ["dead"]},
            {name: "ghost", glyph: "👻", keywords: ["boo"]},
            {name: "robot", glyph: "🤖", keywords: ["ai"]},
            {name: "wave", glyph: "👋", keywords: ["hello", "goodbye", "hi"]},
            {name: "raised_hand", glyph: "✋", keywords: ["stop"]},
            {name: "ok_hand", glyph: "👌", keywords: ["okay"]},
            {name: "pinched_fingers", glyph: "🤌", keywords: ["italian"]},
            {name: "victory", glyph: "✌️", keywords: ["peace"]},
            {name: "crossed_fingers", glyph: "🤞", keywords: ["luck"]},
            {name: "love_you_gesture", glyph: "🤟", keywords: ["rock", "love"]},
            {name: "metal", glyph: "🤘", keywords: ["rock"]},
            {name: "point_right", glyph: "👉", keywords: ["this"]},
            {name: "point_left", glyph: "👈", keywords: ["this"]},
            {name: "point_up_2", glyph: "👆", keywords: ["up"]},
            {name: "point_down", glyph: "👇", keywords: ["down"]},
            {name: "raised_back_of_hand", glyph: "🤚", keywords: ["stop"]},
            {name: "thumbs_up", glyph: "👍", keywords: ["yes", "like"]},
            {name: "+1", glyph: "👍", keywords: ["yes", "like", "approve"]},
            {name: "thumbs_down", glyph: "👎", keywords: ["no", "dislike"]},
            {name: "-1", glyph: "👎", keywords: ["no", "dislike"]},
            {name: "fist_raised", glyph: "✊", keywords: ["fight"]},
            {name: "facepunch", glyph: "👊", keywords: ["punch"]},
            {name: "clap", glyph: "👏", keywords: ["applause"]},
            {name: "pray", glyph: "🙏", keywords: ["thanks", "please"]},
            {name: "handshake", glyph: "🤝", keywords: ["deal"]},
            {name: "muscle", glyph: "💪", keywords: ["strong", "flex"]},
            {name: "eyes", glyph: "👀", keywords: ["look", "watching"]},
            {name: "brain", glyph: "🧠", keywords: ["smart"]},
            {name: "raised_hands", glyph: "🙌", keywords: ["hooray"]},
        ],
    },
    {
        id: "nature",
        label: "Nature",
        icon: "🌿",
        emojis: [
            {name: "dog", glyph: "🐶", keywords: ["puppy"]},
            {name: "cat", glyph: "🐱", keywords: ["kitten"]},
            {name: "mouse", glyph: "🐭", keywords: []},
            {name: "hamster", glyph: "🐹", keywords: []},
            {name: "rabbit", glyph: "🐰", keywords: ["bunny"]},
            {name: "fox", glyph: "🦊", keywords: []},
            {name: "bear", glyph: "🐻", keywords: []},
            {name: "panda", glyph: "🐼", keywords: []},
            {name: "koala", glyph: "🐨", keywords: []},
            {name: "tiger", glyph: "🐯", keywords: []},
            {name: "lion", glyph: "🦁", keywords: []},
            {name: "cow", glyph: "🐮", keywords: []},
            {name: "pig", glyph: "🐷", keywords: []},
            {name: "frog", glyph: "🐸", keywords: []},
            {name: "monkey", glyph: "🐵", keywords: []},
            {name: "chicken", glyph: "🐔", keywords: []},
            {name: "penguin", glyph: "🐧", keywords: []},
            {name: "bird", glyph: "🐦", keywords: []},
            {name: "duck", glyph: "🦆", keywords: []},
            {name: "owl", glyph: "🦉", keywords: []},
            {name: "butterfly", glyph: "🦋", keywords: []},
            {name: "bug", glyph: "🐛", keywords: ["insect", "defect"]},
            {name: "ant", glyph: "🐜", keywords: []},
            {name: "bee", glyph: "🐝", keywords: []},
            {name: "snail", glyph: "🐌", keywords: ["slow"]},
            {name: "spider", glyph: "🕷️", keywords: []},
            {name: "octopus", glyph: "🐙", keywords: []},
            {name: "squid", glyph: "🦑", keywords: []},
            {name: "whale", glyph: "🐳", keywords: []},
            {name: "dolphin", glyph: "🐬", keywords: []},
            {name: "fish", glyph: "🐟", keywords: []},
            {name: "shark", glyph: "🦈", keywords: []},
            {name: "crocodile", glyph: "🐊", keywords: []},
            {name: "turtle", glyph: "🐢", keywords: ["slow"]},
            {name: "snake", glyph: "🐍", keywords: []},
            {name: "dragon", glyph: "🐉", keywords: []},
            {name: "unicorn", glyph: "🦄", keywords: []},
            {name: "horse", glyph: "🐴", keywords: []},
            {name: "elephant", glyph: "🐘", keywords: []},
            {name: "bouquet", glyph: "💐", keywords: ["flowers"]},
            {name: "cherry_blossom", glyph: "🌸", keywords: []},
            {name: "rose", glyph: "🌹", keywords: ["flower"]},
            {name: "sunflower", glyph: "🌻", keywords: []},
            {name: "seedling", glyph: "🌱", keywords: ["plant", "growth"]},
            {name: "evergreen_tree", glyph: "🌲", keywords: ["tree"]},
            {name: "palm_tree", glyph: "🌴", keywords: []},
            {name: "cactus", glyph: "🌵", keywords: []},
            {name: "four_leaf_clover", glyph: "🍀", keywords: ["luck"]},
            {name: "maple_leaf", glyph: "🍁", keywords: ["canada"]},
            {name: "mushroom", glyph: "🍄", keywords: []},
            {name: "earth_americas", glyph: "🌎", keywords: ["world", "globe"]},
            {name: "full_moon", glyph: "🌕", keywords: []},
            {name: "crescent_moon", glyph: "🌙", keywords: []},
            {name: "sun", glyph: "☀️", keywords: []},
            {name: "star", glyph: "⭐", keywords: []},
            {name: "sparkles", glyph: "✨", keywords: ["magic", "shine"]},
            {name: "zap", glyph: "⚡", keywords: ["lightning", "fast"]},
            {name: "fire", glyph: "🔥", keywords: ["lit"]},
            {name: "rainbow", glyph: "🌈", keywords: []},
            {name: "cloud", glyph: "☁️", keywords: []},
            {name: "snowflake", glyph: "❄️", keywords: []},
            {name: "droplet", glyph: "💧", keywords: []},
            {name: "ocean", glyph: "🌊", keywords: ["wave", "water"]},
        ],
    },
    {
        id: "food",
        label: "Food",
        icon: "🍔",
        emojis: [
            {name: "apple", glyph: "🍎", keywords: []},
            {name: "green_apple", glyph: "🍏", keywords: []},
            {name: "orange", glyph: "🍊", keywords: []},
            {name: "lemon", glyph: "🍋", keywords: []},
            {name: "banana", glyph: "🍌", keywords: []},
            {name: "watermelon", glyph: "🍉", keywords: []},
            {name: "grapes", glyph: "🍇", keywords: []},
            {name: "strawberry", glyph: "🍓", keywords: []},
            {name: "peach", glyph: "🍑", keywords: []},
            {name: "cherries", glyph: "🍒", keywords: []},
            {name: "pineapple", glyph: "🍍", keywords: []},
            {name: "coconut", glyph: "🥥", keywords: []},
            {name: "kiwi_fruit", glyph: "🥝", keywords: []},
            {name: "tomato", glyph: "🍅", keywords: []},
            {name: "avocado", glyph: "🥑", keywords: []},
            {name: "eggplant", glyph: "🍆", keywords: []},
            {name: "carrot", glyph: "🥕", keywords: []},
            {name: "corn", glyph: "🌽", keywords: []},
            {name: "hot_pepper", glyph: "🌶️", keywords: ["spicy"]},
            {name: "broccoli", glyph: "🥦", keywords: []},
            {name: "garlic", glyph: "🧄", keywords: []},
            {name: "bread", glyph: "🍞", keywords: []},
            {name: "croissant", glyph: "🥐", keywords: []},
            {name: "pancakes", glyph: "🥞", keywords: []},
            {name: "cheese", glyph: "🧀", keywords: []},
            {name: "meat_on_bone", glyph: "🍖", keywords: []},
            {name: "bacon", glyph: "🥓", keywords: []},
            {name: "hamburger", glyph: "🍔", keywords: ["burger"]},
            {name: "fries", glyph: "🍟", keywords: []},
            {name: "pizza", glyph: "🍕", keywords: []},
            {name: "hotdog", glyph: "🌭", keywords: []},
            {name: "taco", glyph: "🌮", keywords: []},
            {name: "burrito", glyph: "🌯", keywords: []},
            {name: "ramen", glyph: "🍜", keywords: ["noodles"]},
            {name: "spaghetti", glyph: "🍝", keywords: ["pasta"]},
            {name: "sushi", glyph: "🍣", keywords: []},
            {name: "rice_ball", glyph: "🍙", keywords: []},
            {name: "curry", glyph: "🍛", keywords: []},
            {name: "popcorn", glyph: "🍿", keywords: []},
            {name: "cookie", glyph: "🍪", keywords: []},
            {name: "chocolate_bar", glyph: "🍫", keywords: []},
            {name: "candy", glyph: "🍬", keywords: []},
            {name: "doughnut", glyph: "🍩", keywords: ["donut"]},
            {name: "cake", glyph: "🍰", keywords: []},
            {name: "birthday", glyph: "🎂", keywords: ["cake"]},
            {name: "ice_cream", glyph: "🍦", keywords: []},
            {name: "coffee", glyph: "☕", keywords: []},
            {name: "tea", glyph: "🍵", keywords: []},
            {name: "beer", glyph: "🍺", keywords: []},
            {name: "wine_glass", glyph: "🍷", keywords: []},
            {name: "cocktail", glyph: "🍸", keywords: []},
            {name: "champagne", glyph: "🍾", keywords: []},
        ],
    },
    {
        id: "activity",
        label: "Activity",
        icon: "⚽",
        emojis: [
            {name: "soccer", glyph: "⚽", keywords: ["football"]},
            {name: "basketball", glyph: "🏀", keywords: []},
            {name: "football", glyph: "🏈", keywords: []},
            {name: "baseball", glyph: "⚾", keywords: []},
            {name: "tennis", glyph: "🎾", keywords: []},
            {name: "volleyball", glyph: "🏐", keywords: []},
            {name: "rugby_football", glyph: "🏉", keywords: []},
            {name: "8ball", glyph: "🎱", keywords: ["pool"]},
            {name: "ping_pong", glyph: "🏓", keywords: []},
            {name: "badminton", glyph: "🏸", keywords: []},
            {name: "ice_hockey", glyph: "🏒", keywords: []},
            {name: "field_hockey", glyph: "🏑", keywords: []},
            {name: "cricket", glyph: "🏏", keywords: []},
            {name: "goal_net", glyph: "🥅", keywords: []},
            {name: "golf", glyph: "⛳", keywords: []},
            {name: "bow_and_arrow", glyph: "🏹", keywords: ["archery"]},
            {name: "fishing_pole_and_fish", glyph: "🎣", keywords: []},
            {name: "boxing_glove", glyph: "🥊", keywords: []},
            {name: "martial_arts_uniform", glyph: "🥋", keywords: []},
            {name: "skateboard", glyph: "🛹", keywords: []},
            {name: "surfer", glyph: "🏄", keywords: []},
            {name: "swimmer", glyph: "🏊", keywords: []},
            {name: "bicyclist", glyph: "🚴", keywords: []},
            {name: "runner", glyph: "🏃", keywords: []},
            {name: "dancer", glyph: "💃", keywords: []},
            {name: "trophy", glyph: "🏆", keywords: ["winner"]},
            {name: "medal", glyph: "🏅", keywords: []},
            {name: "first_place_medal", glyph: "🥇", keywords: ["gold"]},
            {name: "second_place_medal", glyph: "🥈", keywords: ["silver"]},
            {name: "third_place_medal", glyph: "🥉", keywords: ["bronze"]},
            {name: "tada", glyph: "🎉", keywords: ["party", "celebrate"]},
            {name: "confetti_ball", glyph: "🎊", keywords: []},
            {name: "balloon", glyph: "🎈", keywords: []},
            {name: "gift", glyph: "🎁", keywords: ["present"]},
            {name: "ticket", glyph: "🎫", keywords: []},
            {name: "art", glyph: "🎨", keywords: ["design"]},
            {name: "microphone", glyph: "🎤", keywords: []},
            {name: "headphones", glyph: "🎧", keywords: ["music"]},
            {name: "musical_note", glyph: "🎵", keywords: []},
            {name: "notes", glyph: "🎶", keywords: ["music"]},
            {name: "guitar", glyph: "🎸", keywords: []},
            {name: "video_game", glyph: "🎮", keywords: ["gaming"]},
            {name: "dart", glyph: "🎯", keywords: ["target", "bullseye"]},
            {name: "game_die", glyph: "🎲", keywords: ["dice"]},
        ],
    },
    {
        id: "travel",
        label: "Travel",
        icon: "✈️",
        emojis: [
            {name: "car", glyph: "🚗", keywords: []},
            {name: "taxi", glyph: "🚕", keywords: []},
            {name: "bus", glyph: "🚌", keywords: []},
            {name: "truck", glyph: "🚚", keywords: []},
            {name: "racing_car", glyph: "🏎️", keywords: []},
            {name: "motor_scooter", glyph: "🛵", keywords: []},
            {name: "motorcycle", glyph: "🏍️", keywords: []},
            {name: "bicycle", glyph: "🚲", keywords: ["bike"]},
            {name: "rocket", glyph: "🚀", keywords: ["launch", "space", "fast"]},
            {name: "airplane", glyph: "✈️", keywords: ["plane"]},
            {name: "helicopter", glyph: "🚁", keywords: []},
            {name: "train", glyph: "🚆", keywords: []},
            {name: "metro", glyph: "🚇", keywords: []},
            {name: "tram", glyph: "🚋", keywords: []},
            {name: "ship", glyph: "🚢", keywords: []},
            {name: "boat", glyph: "⛵", keywords: []},
            {name: "anchor", glyph: "⚓", keywords: []},
            {name: "world_map", glyph: "🗺️", keywords: []},
            {name: "compass", glyph: "🧭", keywords: []},
            {name: "mountain", glyph: "⛰️", keywords: []},
            {name: "camping", glyph: "🏕️", keywords: []},
            {name: "beach_with_umbrella", glyph: "🏖️", keywords: ["beach"]},
            {name: "desert", glyph: "🏜️", keywords: []},
            {name: "city_sunset", glyph: "🌇", keywords: ["skyline"]},
            {name: "bridge_at_night", glyph: "🌉", keywords: []},
            {name: "statue_of_liberty", glyph: "🗽", keywords: []},
            {name: "tokyo_tower", glyph: "🗼", keywords: []},
            {name: "house", glyph: "🏠", keywords: []},
            {name: "office", glyph: "🏢", keywords: []},
        ],
    },
    {
        id: "objects",
        label: "Objects",
        icon: "💡",
        emojis: [
            {name: "watch", glyph: "⌚", keywords: []},
            {name: "iphone", glyph: "📱", keywords: ["mobile"]},
            {name: "computer", glyph: "💻", keywords: ["laptop"]},
            {name: "keyboard", glyph: "⌨️", keywords: []},
            {name: "desktop_computer", glyph: "🖥️", keywords: []},
            {name: "printer", glyph: "🖨️", keywords: []},
            {name: "camera", glyph: "📷", keywords: []},
            {name: "video_camera", glyph: "📹", keywords: []},
            {name: "tv", glyph: "📺", keywords: []},
            {name: "floppy_disk", glyph: "💾", keywords: ["save"]},
            {name: "disc", glyph: "💿", keywords: []},
            {name: "battery", glyph: "🔋", keywords: []},
            {name: "electric_plug", glyph: "🔌", keywords: []},
            {name: "bulb", glyph: "💡", keywords: ["idea"]},
            {name: "flashlight", glyph: "🔦", keywords: []},
            {name: "candle", glyph: "🕯️", keywords: []},
            {name: "book", glyph: "📖", keywords: ["read"]},
            {name: "books", glyph: "📚", keywords: []},
            {name: "notebook", glyph: "📓", keywords: []},
            {name: "ledger", glyph: "📒", keywords: []},
            {name: "page_facing_up", glyph: "📄", keywords: ["document"]},
            {name: "scroll", glyph: "📜", keywords: []},
            {name: "bookmark", glyph: "🔖", keywords: []},
            {name: "newspaper", glyph: "📰", keywords: ["news"]},
            {name: "email", glyph: "📧", keywords: ["mail"]},
            {name: "envelope", glyph: "✉️", keywords: []},
            {name: "package", glyph: "📦", keywords: ["box"]},
            {name: "mailbox", glyph: "📫", keywords: []},
            {name: "pencil", glyph: "✏️", keywords: []},
            {name: "black_nib", glyph: "✒️", keywords: []},
            {name: "paperclip", glyph: "📎", keywords: []},
            {name: "scissors", glyph: "✂️", keywords: []},
            {name: "wrench", glyph: "🔧", keywords: []},
            {name: "hammer", glyph: "🔨", keywords: []},
            {name: "gear", glyph: "⚙️", keywords: ["settings"]},
            {name: "toolbox", glyph: "🧰", keywords: []},
            {name: "magnet", glyph: "🧲", keywords: []},
            {name: "lock", glyph: "🔒", keywords: ["security"]},
            {name: "key", glyph: "🔑", keywords: []},
            {name: "bell", glyph: "🔔", keywords: []},
            {name: "loudspeaker", glyph: "📢", keywords: ["megaphone"]},
            {name: "mega", glyph: "📣", keywords: ["announce"]},
            {name: "crystal_ball", glyph: "🔮", keywords: []},
            {name: "money_with_wings", glyph: "💸", keywords: []},
            {name: "moneybag", glyph: "💰", keywords: []},
            {name: "dollar", glyph: "💵", keywords: []},
            {name: "credit_card", glyph: "💳", keywords: []},
            {name: "gem", glyph: "💎", keywords: ["diamond"]},
            {name: "balance_scale", glyph: "⚖️", keywords: []},
            {name: "telescope", glyph: "🔭", keywords: []},
            {name: "microscope", glyph: "🔬", keywords: []},
        ],
    },
    {
        id: "symbols",
        label: "Symbols",
        icon: "❤️",
        emojis: [
            {name: "heart", glyph: "❤️", keywords: ["love"]},
            {name: "orange_heart", glyph: "🧡", keywords: []},
            {name: "yellow_heart", glyph: "💛", keywords: []},
            {name: "green_heart", glyph: "💚", keywords: []},
            {name: "blue_heart", glyph: "💙", keywords: []},
            {name: "purple_heart", glyph: "💜", keywords: []},
            {name: "black_heart", glyph: "🖤", keywords: []},
            {name: "white_heart", glyph: "🤍", keywords: []},
            {name: "broken_heart", glyph: "💔", keywords: []},
            {name: "two_hearts", glyph: "💕", keywords: []},
            {name: "sparkling_heart", glyph: "💖", keywords: []},
            {name: "heartbeat", glyph: "💓", keywords: []},
            {name: "cupid", glyph: "💘", keywords: []},
            {name: "gift_heart", glyph: "💝", keywords: []},
            {name: "exclamation", glyph: "❗", keywords: ["warning"]},
            {name: "question", glyph: "❓", keywords: []},
            {name: "grey_question", glyph: "❔", keywords: []},
            {name: "bangbang", glyph: "‼️", keywords: []},
            {name: "100", glyph: "💯", keywords: ["hundred", "perfect"]},
            {name: "check", glyph: "✅", keywords: ["yes", "done"]},
            {name: "white_check_mark", glyph: "✅", keywords: []},
            {name: "ballot_box_with_check", glyph: "☑️", keywords: []},
            {name: "heavy_check_mark", glyph: "✔️", keywords: []},
            {name: "x", glyph: "❌", keywords: ["no", "wrong"]},
            {name: "heavy_multiplication_x", glyph: "✖️", keywords: []},
            {name: "no_entry", glyph: "⛔", keywords: ["stop"]},
            {name: "prohibited", glyph: "🚫", keywords: []},
            {name: "warning", glyph: "⚠️", keywords: ["caution"]},
            {name: "construction", glyph: "🚧", keywords: []},
            {name: "recycle", glyph: "♻️", keywords: []},
            {name: "plus", glyph: "➕", keywords: []},
            {name: "minus", glyph: "➖", keywords: []},
            {name: "infinity", glyph: "♾️", keywords: []},
            {name: "arrow_up", glyph: "⬆️", keywords: []},
            {name: "arrow_down", glyph: "⬇️", keywords: []},
            {name: "arrow_left", glyph: "⬅️", keywords: []},
            {name: "arrow_right", glyph: "➡️", keywords: []},
            {name: "arrows_counterclockwise", glyph: "🔄", keywords: ["refresh"]},
            {name: "repeat", glyph: "🔁", keywords: []},
            {name: "large_blue_circle", glyph: "🔵", keywords: []},
            {name: "large_orange_diamond", glyph: "🔶", keywords: []},
            {name: "black_circle", glyph: "⚫", keywords: []},
            {name: "white_circle", glyph: "⚪", keywords: []},
            {name: "red_circle", glyph: "🔴", keywords: []},
            {name: "green_circle", glyph: "🟢", keywords: []},
            {name: "yellow_circle", glyph: "🟡", keywords: []},
            {name: "zzz", glyph: "💤", keywords: ["sleep"]},
            {name: "speech_balloon", glyph: "💬", keywords: ["comment"]},
            {name: "thought_balloon", glyph: "💭", keywords: []},
        ],
    },
    {
        id: "flags",
        label: "Flags",
        icon: "🏁",
        emojis: [
            {name: "white_flag", glyph: "🏳️", keywords: []},
            {name: "black_flag", glyph: "🏴", keywords: []},
            {name: "checkered_flag", glyph: "🏁", keywords: ["finish"]},
            {name: "triangular_flag_on_post", glyph: "🚩", keywords: []},
            {name: "rainbow_flag", glyph: "🏳️‍🌈", keywords: ["pride"]},
            {name: "transgender_flag", glyph: "🏳️‍⚧️", keywords: []},
            {name: "pirate_flag", glyph: "🏴‍☠️", keywords: []},
            {name: "flag_us", glyph: "🇺🇸", keywords: ["usa", "america"]},
            {name: "flag_gb", glyph: "🇬🇧", keywords: ["uk", "britain"]},
            {name: "flag_eu", glyph: "🇪🇺", keywords: ["europe"]},
            {name: "flag_fr", glyph: "🇫🇷", keywords: ["france"]},
            {name: "flag_de", glyph: "🇩🇪", keywords: ["germany"]},
            {name: "flag_jp", glyph: "🇯🇵", keywords: ["japan"]},
            {name: "flag_cn", glyph: "🇨🇳", keywords: ["china"]},
            {name: "flag_in", glyph: "🇮🇳", keywords: ["india"]},
            {name: "flag_br", glyph: "🇧🇷", keywords: ["brazil"]},
            {name: "flag_ca", glyph: "🇨🇦", keywords: ["canada"]},
            {name: "flag_au", glyph: "🇦🇺", keywords: ["australia"]},
            {name: "flag_nz", glyph: "🇳🇿", keywords: []},
            {name: "flag_nl", glyph: "🇳🇱", keywords: ["netherlands"]},
            {name: "flag_es", glyph: "🇪🇸", keywords: ["spain"]},
            {name: "flag_it", glyph: "🇮🇹", keywords: ["italy"]},
            {name: "flag_mx", glyph: "🇲🇽", keywords: ["mexico"]},
            {name: "flag_kr", glyph: "🇰🇷", keywords: ["korea"]},
        ],
    },
];

// Flat index for search. Computed once; the picker reuses it across
// every keystroke instead of scanning the category tree.
export interface EmojiSearchEntry extends EmojiEntry {
    category: EmojiCategoryId;
}

export const EMOJI_INDEX: readonly EmojiSearchEntry[] = EMOJI_CATEGORIES.flatMap((c) =>
    c.emojis.map((e) => ({...e, category: c.id})),
);

// Flat name → glyph map for renderers that need to show an emoji given
// only its Zulip name (reaction pills, composer pastes from external
// sources). Renderers live in the main bundle — importing EMOJI_INDEX
// or EMOJI_CATEGORIES would pull in the full picker dataset, but
// tree-shaking keeps this Record on its own if it's the only export
// the renderer touches.
export const EMOJI_GLYPH_BY_NAME: Readonly<Record<string, string>> = (() => {
    const map: Record<string, string> = {};
    for (const cat of EMOJI_CATEGORIES) {
        for (const entry of cat.emojis) {
            map[entry.name] = entry.glyph;
        }
    }
    return map;
})();

// Simple substring search that checks `name` and `keywords`. Case-
// insensitive; matches against the raw token, not individual words, so
// "heart_eyes" matches "heart", "eyes", or "heart_eyes".
export function searchEmojis(query: string, limit = 64): readonly EmojiSearchEntry[] {
    const q = query.trim().toLowerCase();
    if (q === "") return [];
    const hits: EmojiSearchEntry[] = [];
    for (const entry of EMOJI_INDEX) {
        if (entry.name.includes(q) || (entry.keywords ?? []).some((kw) => kw.includes(q))) {
            hits.push(entry);
            if (hits.length >= limit) break;
        }
    }
    return hits;
}
